name: publish

on:
  push:
    branches:
      - master
permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          run_install: true
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - id: publish
        name: publish any-toolkit
        uses: JS-DevTools/npm-publish@v4.1.1
        with:
          package: any-toolkit/package.json
      - id: publish-vitest
        name: publish any-toolkit-vitest
        uses: JS-DevTools/npm-publish@v4.1.1
        with:
          package: any-toolkit-vitest/package.json
      - if: ${{ steps.publish.outputs.type }}
        run:
          echo "# ${{ steps.publish.outputs.version }}" >> "any-toolkit@$GITHUB_STEP_SUMMARY"
          echo "# ${{ steps.publish-vitest.outputs.version }}" >> "any-toolkit-vitest@$GITHUB_STEP_SUMMARY"
