name: publish

on:
  push:
    branches:
      - master
permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          run_install: true
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: verify versions are in sync
        run: |
          V1=$(jq -r .version any-toolkit/package.json)
          V2=$(jq -r .version any-toolkit-vitest/package.json)
          [ "$V1" = "$V2" ] || (echo "Version mismatch: $V1 != $V2" && exit 1)
      - run: pnpm run build
      - run: pnpm run test
      - id: publish
        name: publish any-toolkit
        uses: JS-DevTools/npm-publish@v4.1.1
        with:
          package: any-toolkit/package.json
      - id: publish-vitest
        name: publish any-toolkit-vitest
        uses: JS-DevTools/npm-publish@v4.1.1
        with:
          package: any-toolkit-vitest/package.json
      - if: ${{ steps.publish.outputs.type }}
        run:
          echo "# ${{ steps.publish.outputs.name }}@${{ steps.publish.outputs.version }}" >> "$GITHUB_STEP_SUMMARY"
          echo "# ${{ steps.publish-vitest.outputs.name }}@${{ steps.publish-vitest.outputs.version }}" >> "$GITHUB_STEP_SUMMARY"

  publish-presentation:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          run_install: true
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: pnpm --filter any-toolkit-presentation build -- --base /any-toolkit/
      - uses: actions/upload-pages-artifact@v5
        with:
          path: presentation/dist
      - uses: actions/deploy-pages@v5